### ISSUE TITLE
Info Pane for Developers

### ISSUE THREAD

**Issue by Sachiru** [zacharee/BoredSigns#1]
It would be nice if an info pane for developers would be added that can contain the following data:

Screen FPS
CPU/GPU Temperature
RAM Utilization (in MB)
Battery Discharge Rate (in mA)

(Of course, not all of them in one screen, maybe a temperature widget that shows CPU/GPU/Battery Temps, another widget for Screen FPS and RAM utilization, etc).

**Comment by zacharee** [comment]
The next release should have this. I just need to figure out the GPU temperature part.

**Comment by Sachiru** [comment]
Excellent work, well worth what I paid. Thanks!
