### ISSUE TITLE
Updating build for Oreo

### ISSUE THREAD

**Issue by colin-williams** [zacharee/BoredSigns#12]
I stumbled upon this and read elsewhere stated it will not work for Oreo. v20 has Oreo released. I'm familiar with Java development but not necessarily Android. Does Oreo need a complete rewrite or can you give me some details if I wanted to try to pick it up?

**Comment by zacharee** [comment]
It's already been updated for Oreo.


On Sep 13, 2018 1:23 AM, colin-williams <notifications@github.com> wrote:

I stumbled upon this and read elsewhere stated it will not work for Oreo. v20 has Oreo released. I'm familiar with Java development but not necessarily Android. Does Oreo need a complete rewrite or can you give me some details if I wanted to try to pick it up?

**Comment by colin-williams** [comment]
There was a forum post or similar that I think you authored where you said you were getting rid of the phone and not updating for Oreo. You might want to take that down.
