### ISSUE TITLE
RemoteViews Dpi has changed

### ISSUE THREAD

**Issue by Migushthe2nd** [zacharee/BoredSigns#7]
When changing the Dpi via ADB the BoredSigns app didn't seem to work. After changing it back to 640 it started working again, but now when using adb logcat the system is spamming `D LgeAppWidgetHostViewSignBoard: com.zacharee1.boredsigns's RemoteViews Dpi has changed, 640 -> 640` 
I don't know if this is your app but I suppose there shouldn't be as much spam as there is.

**Comment by zacharee** [comment]
I'm using it on 515 DPI right now without issue. I built the layouts in pixels, so changing the DPI should have no effect.

The log is part of LG's implementation.

**Comment by Migushthe2nd** [comment]
Hmm weird. Mine seemed to keep crashing. I'll try again then.
